# Generated by Django 2.1.1 on 2018-09-28 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='profile',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='block',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='building',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='street',
            field=models.CharField(default='aloha', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
