# Generated by Django 2.1.1 on 2018-11-01 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='ratings',
        ),
    ]
