# Generated by Django 2.1.1 on 2018-11-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_rating_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='ratings',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=1),
        ),
    ]
