# Generated by Django 2.1.1 on 2018-11-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181115_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
