# Generated by Django 2.1.1 on 2018-12-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduel',
            name='_from',
        ),
        migrations.RemoveField(
            model_name='scheduel',
            name='to',
        ),
        migrations.AddField(
            model_name='scheduel',
            name='available_time',
            field=models.CharField(default='d', max_length=120),
            preserve_default=False,
        ),
    ]
