# Generated by Django 2.1.1 on 2018-12-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181213_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduel',
            name='date',
            field=models.CharField(max_length=150),
        ),
    ]
