# Generated by Django 2.1.1 on 2018-09-28 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180928_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='scheduel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Scheduel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheduel',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_schedule', to=settings.AUTH_USER_MODEL),
        ),
    ]
