# Generated by Django 2.1.1 on 2019-01-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181213_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
