# Generated by Django 2.1.1 on 2018-09-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_doctorprofile_scheduel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='google_maps',
            field=models.URLField(max_length=450),
        ),
    ]
