# Generated by Django 2.1.1 on 2018-09-29 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180929_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduel',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_schedule', to='api.DoctorProfile'),
        ),
    ]
