# Generated by Django 2.1.1 on 2018-10-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rating_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduel',
            old_name='time',
            new_name='_from',
        ),
        migrations.AddField(
            model_name='scheduel',
            name='to',
            field=models.TimeField(default='13:25:56'),
            preserve_default=False,
        ),
    ]
